[book]
title = "youyuanwu"
description = "Personal site of youyuanwu"
authors = ["youyuanwu"]
language = "en"
src = "docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/youyuanwu/youyuanwu.github.io"
edit-url-template = "https://github.com/youyuanwu/youyuanwu.github.io/edit/main/{path}"

[output.html.fold]
enable = true
level = 1

[preprocessor.katex]
after = ["links"]
